import {
  RahulBansal,
  Sathvika,
  Naman,
  Ketan,
  Koysha,
  Shambhavi,
  Sunil,
  Kartik,
  Puranjay,
  Pranav_Mahajan,
  Astha_Patel,
  Kesia,
  Viraj_Patel,
  Puranjot,
  Aditya,
} from "../utils/index.js";
export const projects = [
  {
    id: 1,
    index: 0,
    name: "Kalapana-1",
    description:
      "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.",
    modelSrc: "../../public/monkeyDluffy.glb",
    scale: [0.03, 0.03, 0.03],
  },
  {
    id: 2,
    index: 1,
    name: "Kalapana-2",
    description:
      "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.",
    modelSrc: "../../public/tony_chopper.glb",
    scale: [0.03, 0.03, 0.03],
  },
];

export const members = [
  {
    name: "Puranjot Singh Naga",
    linkedin: "https://www.linkedin.com/in/puranjot-singh-92a55326b/",
    email: "puranjotsinghnaga@gmail.com",
    field: "Avionics",
    img: Puranjot,
    position: "Lead",
  },
  {
    name: "Puranjay Kaushik",
    linkedin: "https://www.linkedin.com/in/puranjay-kaushik-2718042b9/",
    email: "punnukaushik29@gmail.com",
    field: "Ground Station",
    position: "Lead",
    img: Puranjay,
  },
  {
    name: "Aditya Vinod Ingle",
    linkedin: "",
    email: "adityaingle932@gmail.com",
    field: "Propulsion",
    img: Aditya,
    position: "Team Head",
  },
  {
    name: "Rahul Bansal",
    linkedin:
      "https://www.linkedin.com/in/rahul-bansal-61971928a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "rahulbansal172004@gmail.com",
    field: "Propulsion",
    img: RahulBansal,
    position: "Sub-Head",
  },
  {
    name: "Varun Choudhary",
    linkedin:
      "https://www.linkedin.com/in/varun-choudhary-4491582b4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "varunchoudhary2003@gmail.com",
    field: "Propulsion",
    img: {},
    position: "Sub-Head",
  },
  {
    name: "Sathvika Balasubramanian",
    linkedin: "linkedin.com/in/sathvika-bala",
    email: "balusathu@hotmail.com",
    field: "Propulsion",
    img: Sathvika,
    position: "Lead",
  },
  {
    name: "Naman Jain",
    linkedin:
      "https://www.linkedin.com/in/naman-jain-526b782b6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "namanjain181018@gmail.com",
    field: "Recovery",
    img: Naman,
    position: "Sub-Head",
  },
  {
    name: "Adu sneha bai",
    linkedin: "https://www.linkedin.com/in/adu-sneha-bai-9b592b211",
    email: "snehabai2004@gmail.com",
    field: "Propulsion",
    img: {},
    position: "Sub-Head",
  },
  {
    name: "Ketan Jain",
    linkedin: "https://www.linkedin.com/in/ketan-jain-71a392257",
    email: "ketanjain1124@gmail.com",
    field: "Propulsion",
    img: Ketan,
    position: "Sub-Head",
  },
  {
    name: "Koysha Shrimali",
    linkedin: "https://www.linkedin.com/in/koysha-shrimali-810823270",
    email: "koysha.shrimali@gmail.com",
    field: "Structure",
    img: Koysha,
    position: "Sub-Head",
  },
  {
    name: "Suneel Kumar Deen",
    linkedin: "https://www.linkedin.com/in/suneel-deen",
    email: "suneelshivpur@gmail.com",
    field: "Structure",
    img: Sunil,
    position: "Lead",
  },
  {
    name: "Kartik Kumar",
    linkedin: "https://www.linkedin.com/in/kartik-kumar-8b4402259/",
    email: "kartikkumaroctober2002@gmail.com",
    field: "Recovery",
    img: Kartik,
    position: "Lead",
  },
  {
    name: "Shambhavi Tiwari",
    linkedin: "www.linkedin.com/in/shambhavi-tiwari-6816322b9",
    email: "shambhavi.tiwari53@gmail.com",
    field: "Simulations",
    img: Shambhavi,
    position: "Sub-Head",
  },
  {
    name: "Madhav Saraswat",
    linkedin: "https://www.linkedin.com/in/madhav-saraswat-724a7426b",
    email: "madhavsaraswatt@gmail.com",
    field: "Structure",
    img: {},
    position: "Sub-Head",
  },
  {
    name: "Pranav Mahajan",
    linkedin: "https://www.linkedin.com/in/pranav-mahajan-8a9471265/",
    email: "hellopranav1039@gmail.com",
    field: "Recovery",
    img: Pranav_Mahajan,
    position: "Sub-Head",
  },
  {
    name: "Astha Patel",
    linkedin:
      "https://www.linkedin.com/in/astha-patel-2588a2271?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "abp199ii@gmail.com",
    field: "Simulations",
    img: Astha_Patel,
    position: "Sub-Head",
  },
  {
    name: "Kesia Ajith",
    linkedin: "https://www.linkedin.com/in/kesia-ajith-aero",
    email: "kesiaajith3@gmail.com",
    field: "Simulations",
    img: Kesia,
    position: "Lead",
  },
  {
    name: "Viraj Patel",
    linkedin: "www.linkedin.com/in/viraj-patel-99701b168",
    email: "patelviraj944@gmail.com",
    field: "Propulsion",
    img: Viraj_Patel,
    position: "Sub-Head",
  },
];
