import rightarrow from "../../public/assets/rightarrow.svg";
import leftarrow from "../../public/assets/leftarrow.svg";
import Aarambhlogo from "../../public/assets/Aarambhlogo.png";
import rahulBansal from "../../public/assets/ProfileImages/Rahul_Bansal.jpg";
import sathvika from "../../public/assets/ProfileImages/sathvika.jpg";
import naman from "../../public/assets/ProfileImages/Naman Jain .jpg";
import ketan from "../../public/assets/ProfileImages/Ketan Jain.jpg";
import koysha from "../../public/assets/ProfileImages/koysha.jpg";
import sunil from "../../public/assets/ProfileImages/sunil.jpg";
import kartik from "../../public/assets/ProfileImages/kartik.jpg";
import puranjay from "../../public/assets/ProfileImages/Puranjay.jpg";
import pranav_Mahajan from "../../public/assets/ProfileImages/Pranav_Mahajan.jpg";
import astha_Patel from "../../public/assets/ProfileImages/Astha_Patel.jpg";
import kesia from "../../public/assets/ProfileImages/Kesia Ajith.jpeg";
import viraj_Patel from "../../public/assets/ProfileImages/Viraj_Patel.jpg";
import Puranjot_Singh from "../../public/assets/ProfileImages/Puranjot_Singh.jpg";
import shambhavi from "../../public/assets/ProfileImages/shambhavi.jpeg";
import aditya from "../../public/assets/ProfileImages/Aditya_ingle.jpg";
export const leftArrow = leftarrow;
export const rightArrrow = rightarrow;
export const AarambhLogo = Aarambhlogo;
export const RahulBansal = rahulBansal;
export const Sathvika = sathvika;
export const Naman = naman;
export const Ketan = ketan;
export const Koysha = koysha;
export const Sunil = sunil;
export const Kartik = kartik;
export const Puranjay = puranjay;
export const Pranav_Mahajan = pranav_Mahajan;
export const Astha_Patel = astha_Patel;
export const Kesia = kesia;
export const Viraj_Patel = viraj_Patel;
export const Puranjot = Puranjot_Singh;
export const Shambhavi = shambhavi;
export const Aditya = aditya;
